<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12.4 Hypothesis testing | Statistics for Business Analytics</title>
  <meta name="description" content="This book covers the main principles of statistics for Business Analytics, focusing on the application side and how analytics and forecasting can be done with conventional statistical models." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="12.4 Hypothesis testing | Statistics for Business Analytics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book covers the main principles of statistics for Business Analytics, focusing on the application side and how analytics and forecasting can be done with conventional statistical models." />
  <meta name="github-repo" content="config-i1/sba" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12.4 Hypothesis testing | Statistics for Business Analytics" />
  
  <meta name="twitter:description" content="This book covers the main principles of statistics for Business Analytics, focusing on the application side and how analytics and forecasting can be done with conventional statistical models." />
  

<meta name="author" content="Ivan Svetunkov" />


<meta name="date" content="2025-10-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="uncertaintyRegressionLine.html"/>
<link rel="next" href="dummyVariables.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script async defer src="https://hypothes.is/embed.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-98538X2YLT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-98538X2YLT');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics for Business Analytics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="what-is-model.html"><a href="what-is-model.html"><i class="fa fa-check"></i><b>1.1</b> What is model?</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="what-is-model.html"><a href="what-is-model.html#modelsMethods"><i class="fa fa-check"></i><b>1.1.1</b> Models, methods et al. </a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="scales.html"><a href="scales.html"><i class="fa fa-check"></i><b>1.2</b> Scales of information</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="scales.html"><a href="scales.html#nominal-scale"><i class="fa fa-check"></i><b>1.2.1</b> Nominal scale</a></li>
<li class="chapter" data-level="1.2.2" data-path="scales.html"><a href="scales.html#ordinal-scale"><i class="fa fa-check"></i><b>1.2.2</b> Ordinal scale</a></li>
<li class="chapter" data-level="1.2.3" data-path="scales.html"><a href="scales.html#interval-scale"><i class="fa fa-check"></i><b>1.2.3</b> Interval scale</a></li>
<li class="chapter" data-level="1.2.4" data-path="scales.html"><a href="scales.html#ratio-scale"><i class="fa fa-check"></i><b>1.2.4</b> Ratio scale</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="typesOfData.html"><a href="typesOfData.html"><i class="fa fa-check"></i><b>1.3</b> Types of data</a></li>
<li class="chapter" data-level="1.4" data-path="sourcesOfUncertainty.html"><a href="sourcesOfUncertainty.html"><i class="fa fa-check"></i><b>1.4</b> Sources of uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="probabilityTheory.html"><a href="probabilityTheory.html"><i class="fa fa-check"></i><b>2</b> Probability theory</a>
<ul>
<li class="chapter" data-level="2.1" data-path="whatIsProbability.html"><a href="whatIsProbability.html"><i class="fa fa-check"></i><b>2.1</b> What is probability?</a></li>
<li class="chapter" data-level="2.2" data-path="whatIsRandomVariable.html"><a href="whatIsRandomVariable.html"><i class="fa fa-check"></i><b>2.2</b> What is random variable?</a></li>
<li class="chapter" data-level="2.3" data-path="probabilityAddition.html"><a href="probabilityAddition.html"><i class="fa fa-check"></i><b>2.3</b> The Addition Law: Calculating “OR” Probability</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="probabilityAddition.html"><a href="probabilityAddition.html#the-general-addition-law"><i class="fa fa-check"></i><b>2.3.1</b> The General Addition Law</a></li>
<li class="chapter" data-level="2.3.2" data-path="probabilityAddition.html"><a href="probabilityAddition.html#special-case-mutually-exclusive-events"><i class="fa fa-check"></i><b>2.3.2</b> Special Case: Mutually Exclusive Events</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="probabilityMultiplication.html"><a href="probabilityMultiplication.html"><i class="fa fa-check"></i><b>2.4</b> Multiplication of probabilities: Calculating “AND” Probability</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="probabilityMultiplication.html"><a href="probabilityMultiplication.html#independent-events"><i class="fa fa-check"></i><b>2.4.1</b> Independent Events</a></li>
<li class="chapter" data-level="2.4.2" data-path="probabilityMultiplication.html"><a href="probabilityMultiplication.html#dependent-events-and-conditional-probability"><i class="fa fa-check"></i><b>2.4.2</b> Dependent Events and Conditional Probability</a></li>
<li class="chapter" data-level="2.4.3" data-path="probabilityMultiplication.html"><a href="probabilityMultiplication.html#general-multiplication-law"><i class="fa fa-check"></i><b>2.4.3</b> General Multiplication Law</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="totalProbability.html"><a href="totalProbability.html"><i class="fa fa-check"></i><b>2.5</b> The Law of Total Probability</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="totalProbability.html"><a href="totalProbability.html#example-faulty-goods-in-a-factory"><i class="fa fa-check"></i><b>2.5.1</b> Example: Faulty Goods in a Factory</a></li>
<li class="chapter" data-level="2.5.2" data-path="totalProbability.html"><a href="totalProbability.html#formalising-the-law-of-total-probability"><i class="fa fa-check"></i><b>2.5.2</b> Formalising the Law of Total Probability</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="BayesTheorem.html"><a href="BayesTheorem.html"><i class="fa fa-check"></i><b>2.6</b> Bayes’ theorem</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="BayesTheorem.html"><a href="BayesTheorem.html#mathematical-derivation"><i class="fa fa-check"></i><b>2.6.1</b> Mathematical derivation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="countDistributions.html"><a href="countDistributions.html"><i class="fa fa-check"></i><b>3</b> Discrete distributions</a>
<ul>
<li class="chapter" data-level="3.1" data-path="what-is-discrete-distribution.html"><a href="what-is-discrete-distribution.html"><i class="fa fa-check"></i><b>3.1</b> What is discrete distribution?</a></li>
<li class="chapter" data-level="3.2" data-path="rvExpectationAndVariance.html"><a href="rvExpectationAndVariance.html"><i class="fa fa-check"></i><b>3.2</b> Expected value and variance of a random variable</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="rvExpectationAndVariance.html"><a href="rvExpectationAndVariance.html#daily-car-sales-at-dicarlo-motors"><i class="fa fa-check"></i><b>3.2.1</b> Daily Car Sales at DiCarlo Motors</a></li>
<li class="chapter" data-level="3.2.2" data-path="rvExpectationAndVariance.html"><a href="rvExpectationAndVariance.html#calculating-the-expected-value-the-mean"><i class="fa fa-check"></i><b>3.2.2</b> Calculating the Expected Value (The Mean)</a></li>
<li class="chapter" data-level="3.2.3" data-path="rvExpectationAndVariance.html"><a href="rvExpectationAndVariance.html#calculating-the-variance-and-standard-deviation"><i class="fa fa-check"></i><b>3.2.3</b> Calculating the Variance and Standard Deviation</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="distributionBernoulli.html"><a href="distributionBernoulli.html"><i class="fa fa-check"></i><b>3.3</b> Bernoulli distribution (Tossing a coin)</a></li>
<li class="chapter" data-level="3.4" data-path="distributionBinomial.html"><a href="distributionBinomial.html"><i class="fa fa-check"></i><b>3.4</b> Binomial distribution (Multiple coin tosses)</a></li>
<li class="chapter" data-level="3.5" data-path="distributionPoisson.html"><a href="distributionPoisson.html"><i class="fa fa-check"></i><b>3.5</b> Poisson distribution (Modelling arrivals)</a></li>
<li class="chapter" data-level="3.6" data-path="distributionUniform.html"><a href="distributionUniform.html"><i class="fa fa-check"></i><b>3.6</b> Discrete Uniform distribution (Rolling a dice)</a></li>
<li class="chapter" data-level="3.7" data-path="distributionNegBin.html"><a href="distributionNegBin.html"><i class="fa fa-check"></i><b>3.7</b> Negative Binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="distributions.html"><a href="distributions.html"><i class="fa fa-check"></i><b>4</b> Continuous distributions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="distributionsContinuousWhat.html"><a href="distributionsContinuousWhat.html"><i class="fa fa-check"></i><b>4.1</b> What is continuous distribution?</a></li>
<li class="chapter" data-level="4.2" data-path="distributionsUniformContinuous.html"><a href="distributionsUniformContinuous.html"><i class="fa fa-check"></i><b>4.2</b> Continuous Uniform distribution</a></li>
<li class="chapter" data-level="4.3" data-path="distributionsNormal.html"><a href="distributionsNormal.html"><i class="fa fa-check"></i><b>4.3</b> Normal distribution</a></li>
<li class="chapter" data-level="4.4" data-path="distributionLogNormal.html"><a href="distributionLogNormal.html"><i class="fa fa-check"></i><b>4.4</b> Log-Normal distribution</a></li>
<li class="chapter" data-level="4.5" data-path="distributionsExponential.html"><a href="distributionsExponential.html"><i class="fa fa-check"></i><b>4.5</b> Exponential distribution</a></li>
<li class="chapter" data-level="4.6" data-path="distributionsConvolution.html"><a href="distributionsConvolution.html"><i class="fa fa-check"></i><b>4.6</b> Convolution of distributions</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="distributionsConvolution.html"><a href="distributionsConvolution.html#distributionsConvolutionDiscrete"><i class="fa fa-check"></i><b>4.6.1</b> Convolution of two discrete distributions</a></li>
<li class="chapter" data-level="4.6.2" data-path="distributionsConvolution.html"><a href="distributionsConvolution.html#distributionsConvolutionContinuous"><i class="fa fa-check"></i><b>4.6.2</b> Convolution of two continuous distributions</a></li>
<li class="chapter" data-level="4.6.3" data-path="distributionsConvolution.html"><a href="distributionsConvolution.html#distributionsConvolutionMaths"><i class="fa fa-check"></i><b>4.6.3</b> Mathematics behind convolutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dataAnalysis.html"><a href="dataAnalysis.html"><i class="fa fa-check"></i><b>5</b> Preliminary data analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dataAnalysisNumerical.html"><a href="dataAnalysisNumerical.html"><i class="fa fa-check"></i><b>5.1</b> Numerical analysis</a></li>
<li class="chapter" data-level="5.2" data-path="dataAnalysisGraphical.html"><a href="dataAnalysisGraphical.html"><i class="fa fa-check"></i><b>5.2</b> Graphical analysis</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="dataAnalysisGraphical.html"><a href="dataAnalysisGraphical.html#one-categoricaldiscrete-variable"><i class="fa fa-check"></i><b>5.2.1</b> One categorical/discrete variable</a></li>
<li class="chapter" data-level="5.2.2" data-path="dataAnalysisGraphical.html"><a href="dataAnalysisGraphical.html#two-categoricaldiscrete-variables"><i class="fa fa-check"></i><b>5.2.2</b> Two categorical/discrete variables</a></li>
<li class="chapter" data-level="5.2.3" data-path="dataAnalysisGraphical.html"><a href="dataAnalysisGraphical.html#one-numerical-continuous-variable"><i class="fa fa-check"></i><b>5.2.3</b> One numerical continuous variable</a></li>
<li class="chapter" data-level="5.2.4" data-path="dataAnalysisGraphical.html"><a href="dataAnalysisGraphical.html#two-continuous-numerical-variables"><i class="fa fa-check"></i><b>5.2.4</b> Two continuous numerical variables</a></li>
<li class="chapter" data-level="5.2.5" data-path="dataAnalysisGraphical.html"><a href="dataAnalysisGraphical.html#a-mixture-of-variables"><i class="fa fa-check"></i><b>5.2.5</b> A mixture of variables</a></li>
<li class="chapter" data-level="5.2.6" data-path="dataAnalysisGraphical.html"><a href="dataAnalysisGraphical.html#plot-for-several-variables"><i class="fa fa-check"></i><b>5.2.6</b> Plot for several variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="PopulationSampling.html"><a href="PopulationSampling.html"><i class="fa fa-check"></i><b>6</b> Population and sampling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>6.1</b> An Introduction to Sampling</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="sampling.html"><a href="sampling.html#the-wisdom-and-folly-of-crowds"><i class="fa fa-check"></i><b>6.1.1</b> The Wisdom and Folly of Crowds</a></li>
<li class="chapter" data-level="6.1.2" data-path="sampling.html"><a href="sampling.html#populations-samples-parameters-and-statistics"><i class="fa fa-check"></i><b>6.1.2</b> Populations, Samples, Parameters, and Statistics</a></li>
<li class="chapter" data-level="6.1.3" data-path="sampling.html"><a href="sampling.html#sampleSimpleRandom"><i class="fa fa-check"></i><b>6.1.3</b> Simple Random Sampling (SRS)</a></li>
<li class="chapter" data-level="6.1.4" data-path="sampling.html"><a href="sampling.html#sampleSystematic"><i class="fa fa-check"></i><b>6.1.4</b> Systematic Sampling</a></li>
<li class="chapter" data-level="6.1.5" data-path="sampling.html"><a href="sampling.html#stratified-sampling"><i class="fa fa-check"></i><b>6.1.5</b> Stratified Sampling</a></li>
<li class="chapter" data-level="6.1.6" data-path="sampling.html"><a href="sampling.html#cluster-sampling"><i class="fa fa-check"></i><b>6.1.6</b> Cluster Sampling</a></li>
<li class="chapter" data-level="6.1.7" data-path="sampling.html"><a href="sampling.html#quota-sampling"><i class="fa fa-check"></i><b>6.1.7</b> Quota Sampling</a></li>
<li class="chapter" data-level="6.1.8" data-path="sampling.html"><a href="sampling.html#convenience-sampling"><i class="fa fa-check"></i><b>6.1.8</b> Convenience Sampling</a></li>
<li class="chapter" data-level="6.1.9" data-path="sampling.html"><a href="sampling.html#voluntary-response-sampling"><i class="fa fa-check"></i><b>6.1.9</b> Voluntary Response Sampling</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="LLN.html"><a href="LLN.html"><i class="fa fa-check"></i><b>6.2</b> Law of Large Numbers</a></li>
<li class="chapter" data-level="6.3" data-path="CLT.html"><a href="CLT.html"><i class="fa fa-check"></i><b>6.3</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="6.4" data-path="estimatesProperties.html"><a href="estimatesProperties.html"><i class="fa fa-check"></i><b>6.4</b> Properties of estimators</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="estimatesProperties.html"><a href="estimatesProperties.html#estimatesPropertiesBias"><i class="fa fa-check"></i><b>6.4.1</b> Bias</a></li>
<li class="chapter" data-level="6.4.2" data-path="estimatesProperties.html"><a href="estimatesProperties.html#estimatesPropertiesEfficiency"><i class="fa fa-check"></i><b>6.4.2</b> Efficiency</a></li>
<li class="chapter" data-level="6.4.3" data-path="estimatesProperties.html"><a href="estimatesProperties.html#estimatesPropertiesConsistency"><i class="fa fa-check"></i><b>6.4.3</b> Consistency</a></li>
<li class="chapter" data-level="6.4.4" data-path="estimatesProperties.html"><a href="estimatesProperties.html#asymptoticNormality"><i class="fa fa-check"></i><b>6.4.4</b> Asymptotic normality</a></li>
<li class="chapter" data-level="6.4.5" data-path="estimatesProperties.html"><a href="estimatesProperties.html#efficiencyVSBias"><i class="fa fa-check"></i><b>6.4.5</b> Why having biased estimate can be better than having the inefficient one?</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="confidenceInterval.html"><a href="confidenceInterval.html"><i class="fa fa-check"></i><b>6.5</b> Confidence interval</a></li>
<li class="chapter" data-level="6.6" data-path="predictionInterval.html"><a href="predictionInterval.html"><i class="fa fa-check"></i><b>6.6</b> Prediction interval</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="hypothesisTesting.html"><a href="hypothesisTesting.html"><i class="fa fa-check"></i><b>7</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="hypothesisTestingBasics.html"><a href="hypothesisTestingBasics.html"><i class="fa fa-check"></i><b>7.1</b> Basic idea</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="hypothesisTestingBasics.html"><a href="hypothesisTestingBasics.html#hypothesisTestingMistakes"><i class="fa fa-check"></i><b>7.1.1</b> Common mistakes related to hypothesis testing</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="typeErrors.html"><a href="typeErrors.html"><i class="fa fa-check"></i><b>7.2</b> Errors of types 0, I and II</a></li>
<li class="chapter" data-level="7.3" data-path="powerOfTheTest.html"><a href="powerOfTheTest.html"><i class="fa fa-check"></i><b>7.3</b> Power of a test</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="powerOfTheTest.html"><a href="powerOfTheTest.html#visual-explanation"><i class="fa fa-check"></i><b>7.3.1</b> Visual explanation</a></li>
<li class="chapter" data-level="7.3.2" data-path="powerOfTheTest.html"><a href="powerOfTheTest.html#PowerMathematical"><i class="fa fa-check"></i><b>7.3.2</b> Mathematical explantion</a></li>
<li class="chapter" data-level="7.3.3" data-path="powerOfTheTest.html"><a href="powerOfTheTest.html#expected-power-of-a-test"><i class="fa fa-check"></i><b>7.3.3</b> Expected power of a test</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="significance.html"><a href="significance.html"><i class="fa fa-check"></i><b>7.4</b> Statistical and practical significance</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="statisticalTests.html"><a href="statisticalTests.html"><i class="fa fa-check"></i><b>8</b> Statistical tests</a>
<ul>
<li class="chapter" data-level="8.1" data-path="statisticalTestsOneSampleMean.html"><a href="statisticalTestsOneSampleMean.html"><i class="fa fa-check"></i><b>8.1</b> One-sample tests about mean</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="statisticalTestsOneSampleMean.html"><a href="statisticalTestsOneSampleMean.html#statisticalTestsOneSampleMeanZ"><i class="fa fa-check"></i><b>8.1.1</b> z-test</a></li>
<li class="chapter" data-level="8.1.2" data-path="statisticalTestsOneSampleMean.html"><a href="statisticalTestsOneSampleMean.html#statisticalTestsOneSampleMeanT"><i class="fa fa-check"></i><b>8.1.2</b> t-test</a></li>
<li class="chapter" data-level="8.1.3" data-path="statisticalTestsOneSampleMean.html"><a href="statisticalTestsOneSampleMean.html#non-parametric-one-sample-wilcoxon-test"><i class="fa fa-check"></i><b>8.1.3</b> Non-parametric, one-sample Wilcoxon test</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="statisticalTestsOneSampleVariance.html"><a href="statisticalTestsOneSampleVariance.html"><i class="fa fa-check"></i><b>8.2</b> One-sample test about variance</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>9</b> Measuring relations between variables</a>
<ul>
<li class="chapter" data-level="9.1" data-path="correlationsNominal.html"><a href="correlationsNominal.html"><i class="fa fa-check"></i><b>9.1</b> Nominal scale</a></li>
<li class="chapter" data-level="9.2" data-path="ordinal-scale-1.html"><a href="ordinal-scale-1.html"><i class="fa fa-check"></i><b>9.2</b> Ordinal scale</a></li>
<li class="chapter" data-level="9.3" data-path="correlationCoefficient.html"><a href="correlationCoefficient.html"><i class="fa fa-check"></i><b>9.3</b> Numerical scale</a></li>
<li class="chapter" data-level="9.4" data-path="correlationsMixed.html"><a href="correlationsMixed.html"><i class="fa fa-check"></i><b>9.4</b> Mixed scales</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="simpleLinearRegression.html"><a href="simpleLinearRegression.html"><i class="fa fa-check"></i><b>10</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="OLS.html"><a href="OLS.html"><i class="fa fa-check"></i><b>10.1</b> Ordinary Least Squares (OLS)</a></li>
<li class="chapter" data-level="10.2" data-path="SLRCovariance.html"><a href="SLRCovariance.html"><i class="fa fa-check"></i><b>10.2</b> Covariance, correlation and SLR</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="SLRCovariance.html"><a href="SLRCovariance.html#covariance"><i class="fa fa-check"></i><b>10.2.1</b> Covariance</a></li>
<li class="chapter" data-level="10.2.2" data-path="SLRCovariance.html"><a href="SLRCovariance.html#SLRCovarianceCor"><i class="fa fa-check"></i><b>10.2.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="OLSResiduals.html"><a href="OLSResiduals.html"><i class="fa fa-check"></i><b>10.3</b> Residuals of model estimated via OLS</a></li>
<li class="chapter" data-level="10.4" data-path="linearRegressionSimpleQualityOfFit.html"><a href="linearRegressionSimpleQualityOfFit.html"><i class="fa fa-check"></i><b>10.4</b> Quality of a fit</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="linearRegressionSimpleQualityOfFit.html"><a href="linearRegressionSimpleQualityOfFit.html#linearRegressionSimpleQualityOfFitSSE"><i class="fa fa-check"></i><b>10.4.1</b> Sums of squares</a></li>
<li class="chapter" data-level="10.4.2" data-path="linearRegressionSimpleQualityOfFit.html"><a href="linearRegressionSimpleQualityOfFit.html#coefficient-of-determination-r2"><i class="fa fa-check"></i><b>10.4.2</b> Coefficient of determination, R<span class="math inline">\(^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="what-about-the-timber-lend-company.html"><a href="what-about-the-timber-lend-company.html"><i class="fa fa-check"></i><b>10.5</b> What about the “Timber Lend” company?</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="linearRegression.html"><a href="linearRegression.html"><i class="fa fa-check"></i><b>11</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="linearRegression.html"><a href="linearRegression.html#TrueModel"><i class="fa fa-check"></i><b>11.0.1</b> A couple of notes about the “true” model</a></li>
<li class="chapter" data-level="11.1" data-path="OLSMLR.html"><a href="OLSMLR.html"><i class="fa fa-check"></i><b>11.1</b> OLS estimation</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="OLSMLR.html"><a href="OLSMLR.html#application"><i class="fa fa-check"></i><b>11.1.1</b> Application</a></li>
<li class="chapter" data-level="11.1.2" data-path="OLSMLR.html"><a href="OLSMLR.html#OLSMLRMaths"><i class="fa fa-check"></i><b>11.1.2</b> A bit of maths</a></li>
<li class="chapter" data-level="11.1.3" data-path="OLSMLR.html"><a href="OLSMLR.html#properties-of-the-ols-estimators"><i class="fa fa-check"></i><b>11.1.3</b> Properties of the OLS Estimators</a></li>
<li class="chapter" data-level="11.1.4" data-path="OLSMLR.html"><a href="OLSMLR.html#GaussMarkov"><i class="fa fa-check"></i><b>11.1.4</b> Gauss-Markov theorem</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="linearRegressionMultipleQualityOfFit.html"><a href="linearRegressionMultipleQualityOfFit.html"><i class="fa fa-check"></i><b>11.2</b> Quality of a fit</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="linearRegressionMultipleQualityOfFit.html"><a href="linearRegressionMultipleQualityOfFit.html#common-mistakes-related-to-quality-of-a-fit"><i class="fa fa-check"></i><b>11.2.1</b> Common mistakes related to quality of a fit</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="linearRegressionInterpretation.html"><a href="linearRegressionInterpretation.html"><i class="fa fa-check"></i><b>11.3</b> Interpretation of parameters</a></li>
<li class="chapter" data-level="11.4" data-path="linearRegressionPrediction.html"><a href="linearRegressionPrediction.html"><i class="fa fa-check"></i><b>11.4</b> Prediction with regression</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="uncertaintyRegression.html"><a href="uncertaintyRegression.html"><i class="fa fa-check"></i><b>12</b> Uncertainty in regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="uncertaintyRegressionCov.html"><a href="uncertaintyRegressionCov.html"><i class="fa fa-check"></i><b>12.1</b> Covariance matrix of parameters</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="uncertaintyRegressionCov.html"><a href="uncertaintyRegressionCov.html#bootstrap-based-matrix"><i class="fa fa-check"></i><b>12.1.1</b> Bootstrap-based matrix</a></li>
<li class="chapter" data-level="12.1.2" data-path="uncertaintyRegressionCov.html"><a href="uncertaintyRegressionCov.html#analytical-solution"><i class="fa fa-check"></i><b>12.1.2</b> Analytical solution</a></li>
<li class="chapter" data-level="12.1.3" data-path="uncertaintyRegressionCov.html"><a href="uncertaintyRegressionCov.html#uncertaintyRegressionCovMaths"><i class="fa fa-check"></i><b>12.1.3</b> Mathematical derivation</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="uncertaintyRegressionCI.html"><a href="uncertaintyRegressionCI.html"><i class="fa fa-check"></i><b>12.2</b> Confidence intervals of parameters</a></li>
<li class="chapter" data-level="12.3" data-path="uncertaintyRegressionLine.html"><a href="uncertaintyRegressionLine.html"><i class="fa fa-check"></i><b>12.3</b> Regression line related uncertainty</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="uncertaintyRegressionLine.html"><a href="uncertaintyRegressionLine.html#uncertaintyRegressionLineConfidence"><i class="fa fa-check"></i><b>12.3.1</b> Confidence interval</a></li>
<li class="chapter" data-level="12.3.2" data-path="uncertaintyRegressionLine.html"><a href="uncertaintyRegressionLine.html#uncertaintyRegressionLinePrediction"><i class="fa fa-check"></i><b>12.3.2</b> Prediction interval</a></li>
<li class="chapter" data-level="12.3.3" data-path="uncertaintyRegressionLine.html"><a href="uncertaintyRegressionLine.html#uncertaintyRegressionLineMaths"><i class="fa fa-check"></i><b>12.3.3</b> Derivations of the variance in regression</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="uncertaintyRegressionHypothesis.html"><a href="uncertaintyRegressionHypothesis.html"><i class="fa fa-check"></i><b>12.4</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="uncertaintyRegressionHypothesis.html"><a href="uncertaintyRegressionHypothesis.html#regression-parameters"><i class="fa fa-check"></i><b>12.4.1</b> Regression parameters</a></li>
<li class="chapter" data-level="12.4.2" data-path="uncertaintyRegressionHypothesis.html"><a href="uncertaintyRegressionHypothesis.html#regression-line"><i class="fa fa-check"></i><b>12.4.2</b> Regression line</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="dummyVariables.html"><a href="dummyVariables.html"><i class="fa fa-check"></i><b>13</b> Regression with categorical variables</a>
<ul>
<li class="chapter" data-level="13.1" data-path="dummy-variables-for-the-intercept.html"><a href="dummy-variables-for-the-intercept.html"><i class="fa fa-check"></i><b>13.1</b> Dummy variables for the intercept</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="dummy-variables-for-the-intercept.html"><a href="dummy-variables-for-the-intercept.html#dummy-variables-trap"><i class="fa fa-check"></i><b>13.1.1</b> Dummy variables trap</a></li>
<li class="chapter" data-level="13.1.2" data-path="dummy-variables-for-the-intercept.html"><a href="dummy-variables-for-the-intercept.html#what-about-the-variables-in-the-ordinal-scale"><i class="fa fa-check"></i><b>13.1.2</b> What about the variables in the ordinal scale?</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="categorical-variables-for-the-slope.html"><a href="categorical-variables-for-the-slope.html"><i class="fa fa-check"></i><b>13.2</b> Categorical variables for the slope</a></li>
<li class="chapter" data-level="13.3" data-path="a-bit-of-maths.html"><a href="a-bit-of-maths.html"><i class="fa fa-check"></i><b>13.3</b> A bit of maths</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="variablesTransformations.html"><a href="variablesTransformations.html"><i class="fa fa-check"></i><b>14</b> Variables transformations</a>
<ul>
<li class="chapter" data-level="14.1" data-path="example-of-application.html"><a href="example-of-application.html"><i class="fa fa-check"></i><b>14.1</b> Example of application</a></li>
<li class="chapter" data-level="14.2" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html"><i class="fa fa-check"></i><b>14.2</b> Types of variables transformations</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#linear-model"><i class="fa fa-check"></i><b>14.2.1</b> Linear model</a></li>
<li class="chapter" data-level="14.2.2" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#log-log-model"><i class="fa fa-check"></i><b>14.2.2</b> Log-Log model</a></li>
<li class="chapter" data-level="14.2.3" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#log-linear-model"><i class="fa fa-check"></i><b>14.2.3</b> Log-linear model</a></li>
<li class="chapter" data-level="14.2.4" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#linear-log-model"><i class="fa fa-check"></i><b>14.2.4</b> Linear-Log model</a></li>
<li class="chapter" data-level="14.2.5" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#square-root-model"><i class="fa fa-check"></i><b>14.2.5</b> Square root model</a></li>
<li class="chapter" data-level="14.2.6" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#quadratic-model"><i class="fa fa-check"></i><b>14.2.6</b> Quadratic model</a></li>
<li class="chapter" data-level="14.2.7" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#polynomial-model"><i class="fa fa-check"></i><b>14.2.7</b> Polynomial model</a></li>
<li class="chapter" data-level="14.2.8" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#box-cox-transform"><i class="fa fa-check"></i><b>14.2.8</b> Box-Cox transform</a></li>
<li class="chapter" data-level="14.2.9" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#logistic-transform"><i class="fa fa-check"></i><b>14.2.9</b> Logistic transform</a></li>
<li class="chapter" data-level="14.2.10" data-path="types-of-variables-transformations.html"><a href="types-of-variables-transformations.html#summary"><i class="fa fa-check"></i><b>14.2.10</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="assumptions.html"><a href="assumptions.html"><i class="fa fa-check"></i><b>15</b> Statistical models assumptions</a>
<ul>
<li class="chapter" data-level="15.1" data-path="assumptionsCorrectModel.html"><a href="assumptionsCorrectModel.html"><i class="fa fa-check"></i><b>15.1</b> Model is correctly specified</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="assumptionsCorrectModel.html"><a href="assumptionsCorrectModel.html#assumptionsCorrectModelOmitted"><i class="fa fa-check"></i><b>15.1.1</b> Omitted variables</a></li>
<li class="chapter" data-level="15.1.2" data-path="assumptionsCorrectModel.html"><a href="assumptionsCorrectModel.html#assumptionsCorrectModelRedundant"><i class="fa fa-check"></i><b>15.1.2</b> Redundant variables</a></li>
<li class="chapter" data-level="15.1.3" data-path="assumptionsCorrectModel.html"><a href="assumptionsCorrectModel.html#assumptionsCorrectModelTransformations"><i class="fa fa-check"></i><b>15.1.3</b> Transformations</a></li>
<li class="chapter" data-level="15.1.4" data-path="assumptionsCorrectModel.html"><a href="assumptionsCorrectModel.html#assumptionsCorrectModelOutliers"><i class="fa fa-check"></i><b>15.1.4</b> Outliers</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="assumptionsResidualsAreIID.html"><a href="assumptionsResidualsAreIID.html"><i class="fa fa-check"></i><b>15.2</b> Residuals are i.i.d.</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="assumptionsResidualsAreIID.html"><a href="assumptionsResidualsAreIID.html#assumptionsResidualsAreIIDAutocorrelations"><i class="fa fa-check"></i><b>15.2.1</b> No autocorrelations</a></li>
<li class="chapter" data-level="15.2.2" data-path="assumptionsResidualsAreIID.html"><a href="assumptionsResidualsAreIID.html#assumptionsResidualsAreIIDHomoscedasticity"><i class="fa fa-check"></i><b>15.2.2</b> Homoscedastic residuals</a></li>
<li class="chapter" data-level="15.2.3" data-path="assumptionsResidualsAreIID.html"><a href="assumptionsResidualsAreIID.html#assumptionsResidualsAreIIDMean"><i class="fa fa-check"></i><b>15.2.3</b> Mean of residuals</a></li>
<li class="chapter" data-level="15.2.4" data-path="assumptionsResidualsAreIID.html"><a href="assumptionsResidualsAreIID.html#assumptionsDistribution"><i class="fa fa-check"></i><b>15.2.4</b> Distributional assumptions</a></li>
<li class="chapter" data-level="15.2.5" data-path="assumptionsResidualsAreIID.html"><a href="assumptionsResidualsAreIID.html#assumptionsDistributionFixed"><i class="fa fa-check"></i><b>15.2.5</b> Distribution does not change</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="assumptionsXreg.html"><a href="assumptionsXreg.html"><i class="fa fa-check"></i><b>15.3</b> The explanatory variables are not correlated with anything but the response variable</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="assumptionsXreg.html"><a href="assumptionsXreg.html#assumptionsXregMulti"><i class="fa fa-check"></i><b>15.3.1</b> Multicollinearity</a></li>
<li class="chapter" data-level="15.3.2" data-path="assumptionsXreg.html"><a href="assumptionsXreg.html#assumptionsXregEndogeneity"><i class="fa fa-check"></i><b>15.3.2</b> Endogeneity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="likelihoodApproach.html"><a href="likelihoodApproach.html"><i class="fa fa-check"></i><b>16</b> Likelihood Approach</a>
<ul>
<li class="chapter" data-level="16.1" data-path="likelihoodInR.html"><a href="likelihoodInR.html"><i class="fa fa-check"></i><b>16.1</b> An example in R</a></li>
<li class="chapter" data-level="16.2" data-path="likelihoodApproachMaths.html"><a href="likelihoodApproachMaths.html"><i class="fa fa-check"></i><b>16.2</b> Mathematical explanation</a></li>
<li class="chapter" data-level="16.3" data-path="statisticsNumberOfParameters.html"><a href="statisticsNumberOfParameters.html"><i class="fa fa-check"></i><b>16.3</b> Calculating number of parameters in models</a></li>
<li class="chapter" data-level="16.4" data-path="informationCriteria.html"><a href="informationCriteria.html"><i class="fa fa-check"></i><b>16.4</b> Information criteria</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="informationCriteria.html"><a href="informationCriteria.html#informationCriteriaIdea"><i class="fa fa-check"></i><b>16.4.1</b> The idea</a></li>
<li class="chapter" data-level="16.4.2" data-path="informationCriteria.html"><a href="informationCriteria.html#informationCriteriaMistakes"><i class="fa fa-check"></i><b>16.4.2</b> Common confusions related to information criteria</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="uncertaintyModel.html"><a href="uncertaintyModel.html"><i class="fa fa-check"></i><b>17</b> Uncertainty about the model form</a>
<ul>
<li class="chapter" data-level="17.1" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html"><i class="fa fa-check"></i><b>17.1</b> Bias-variance tradeoff</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#graphical-explanation"><i class="fa fa-check"></i><b>17.1.1</b> Graphical explanation</a></li>
<li class="chapter" data-level="17.1.2" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#mathematical-explanation"><i class="fa fa-check"></i><b>17.1.2</b> Mathematical explanation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics for Business Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b><a href="open.html#open">Open Review</a></b>. I want your feedback to make the book better for you and other readers. To add your annotation, <span style="background-color: #3297FD; color: white">select some text</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. To see the annotations of others, click the button in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="uncertaintyRegressionHypothesis" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Hypothesis testing<a href="uncertaintyRegressionHypothesis.html#uncertaintyRegressionHypothesis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the regression context, an analyst is often interested in understanding whether a specific effect exists or not. This is usually done using the hypothesis testing instrument, which we will discuss in this section. But before we do that, we will approach this problem from a slightly non-conventional perspective, using the connection between hypothesis testing and confidence interval.</p>
<p>What does “effect exists” mean in statistical terms? It means that we found some evidence based on our data and model that the value of a parameter is significantly different from zero on some pre-selected level. Formally, this hypothesis is formulated as:
<span class="math display" id="eq:regressionHypothesis01">\[\begin{equation}
\begin{aligned}
\mathrm{H}_0: \beta_i = 0 \\
\mathrm{H}_1: \beta_i \neq 0
\end{aligned} .
\tag{12.20}
\end{equation}\]</span>
where <span class="math inline">\(\beta_i\)</span> is the true parameter in the population. The idea is to make some conclusions about what happens in population based on a specific sample of data <strong>and</strong> the estimated model.</p>
<p>Coming back to the example in Section <a href="uncertaintyRegressionCI.html#uncertaintyRegressionCI">12.2</a>, the whole hypothesis testing process implies that the distribution of the estimates of parameter for <code>materials</code> lies either consistently above zero or consistently below it (in our case, it is above). Figure <a href="uncertaintyRegressionHypothesis.html#fig:costsModelMLRCImaterials">12.9</a> demonstrates the distribution we obtained from the bootstrap in the beginning of this chapter and the 95% confidence interval based on the normal approximation of the distribution.</p>
<div class="figure"><span style="display:block;" id="fig:costsModelMLRCImaterials"></span>
<img src="Svetunkov---Statistics-for-Business-Analytics_files/figure-html/costsModelMLRCImaterials-1.png" alt="Parameter uncertainty in the estimated model for the materials variable." width="672" />
<p class="caption">
Figure 12.9: Parameter uncertainty in the estimated model for the materials variable.
</p>
</div>
<p>The 95% confidence level corresponds to the 5% significance level. We see from Figure <a href="uncertaintyRegressionHypothesis.html#fig:costsModelMLRCImaterials">12.9</a> that the variability of the estimate of the parameter is substantially above zero. This probably means that if we increase the sample size and continue constructing the interval, the true value will be somewhere inside and it must be not equal to zero. We use the word “<em>probably</em>” here because we could always make a mistake based on a specific sample or because the model was incorrectly specified. Still, we would be inclined to conclude on the 5% significance level that the effect is indeed non-zero.</p>
<div class="remark">
<p><span id="unlabeled-div-55" class="remark"><em>Remark</em>. </span>In hypothesis testing, if we formulate the alternative one as inequality (as it was done in <a href="uncertaintyRegressionHypothesis.html#eq:regressionHypothesis01">(12.20)</a>), we cannot say whether the effect is positive or negative. We can only conclude whether it is or it is not zero on the pre-specified significance level.</p>
</div>
<p>If we bring this idea further, we can also conclude that the effect is not equal to 0.4 (that value is outside of the interval and in the left tail of the distribution), and surely not 1.5 (it is in the right tail). We can say that by directly looking at the confidence interval, and, arguably, it provides more information than a critical value or a p-value (we will discuss them later in this section), which would only compare the sample value with zero. But this also shows us what the hypothesis testing is all about: checking whether the tested value is inside the non-rejection interval or not. But can we make solid conclusions about the effect based on the results of the hypothesis testing?</p>
<p>Figure <a href="uncertaintyRegressionHypothesis.html#fig:costsModelMLRCIWithZero">12.10</a> shows the distribution of estimates of some hypothetical parameter in a regression model together with the 95% confidence interval.</p>
<div class="figure"><span style="display:block;" id="fig:costsModelMLRCIWithZero"></span>
<img src="Svetunkov---Statistics-for-Business-Analytics_files/figure-html/costsModelMLRCIWithZero-1.png" alt="Parameter uncertainty of a hypothetical parameter." width="672" />
<p class="caption">
Figure 12.10: Parameter uncertainty of a hypothetical parameter.
</p>
</div>
<p>According to Figure <a href="uncertaintyRegressionHypothesis.html#fig:costsModelMLRCIWithZero">12.10</a>, the zero is included in the interval, so we would fail to reject the hypothesis that the effect is zero on the 5% significance level. This is because there is a chance that this distribution would shift to the left with the increase of the sample size and would become centered around zero. Does this mean that there is no effect? No, because we do not know what happens in population, we are making conclusions based on the limited sample and a specific model.</p>
<p>We can also notice that if we were to formulate a different hypothesis, for example, that the parameter is equal to one, we would fail to reject it on the 5% significance level as well. In fact, we would fail to reject the hypotheses on the 5% significance level that the true parameter equals to 0.5, 1.5 and anything between -1.46 and 2.46. Neither of this tells us anything definite about the true value of parameter. The true conclusion of hypothesis testing in this example is that <strong>we do not know</strong> what the true value of the effect is.</p>
<p>We personally think that the confidence interval shows this idea more clearly, than the conventional hypothesis testing, not hiding anything.</p>
<p>Now we will discuss the classical hypothesis testing in regression.</p>
<div id="regression-parameters" class="section level3 hasAnchor" number="12.4.1">
<h3><span class="header-section-number">12.4.1</span> Regression parameters<a href="uncertaintyRegressionHypothesis.html#regression-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The logic of hypothesis testing in regression is very similar to the one discussed in Section <a href="hypothesisTesting.html#hypothesisTesting">7</a>. To make it more practical, consider the regression that we have already estimated in this chapter and the coefficient for the variable <code>materials</code>, which equals to 0.8706. To test the hypothesis about a parameter in regression, we need to follow the procedure, described in Section <a href="hypothesisTesting.html#hypothesisTesting">7</a>.</p>
<p>First step is to formulate the null and alternative hypotheses. As discussed earlier in this section, the conventional way of doing that is by checking whether the true value of parameter is zero in the population:
<span class="math display">\[\begin{equation*}
\begin{aligned}
\mathrm{H}_0: \beta_i = 0 \\
\mathrm{H}_1: \beta_i \neq 0
\end{aligned} .
\end{equation*}\]</span></p>
<p>Visually, the null and alternative hypotheses can be represented as shown in Figure <a href="uncertaintyRegressionHypothesis.html#fig:costModelHypotheses">12.11</a>.</p>
<div class="figure"><span style="display:block;" id="fig:costModelHypotheses"></span>
<img src="Svetunkov---Statistics-for-Business-Analytics_files/figure-html/costModelHypotheses-1.png" alt="Graphical presentation of null and alternative hypothesis in regression context." width="672" />
<p class="caption">
Figure 12.11: Graphical presentation of null and alternative hypothesis in regression context.
</p>
</div>
<p>The image on the left in Figure <a href="uncertaintyRegressionHypothesis.html#fig:costModelHypotheses">12.11</a> demonstrates how the true model could look if the null hypothesis was true - it would be just a straight line, parallel to x-axis. This would imply that with the increase of the material costs, the overall costs do not change. The image on the right in Figure <a href="uncertaintyRegressionHypothesis.html#fig:costModelHypotheses">12.11</a> demonstrates the alternative situation, when the parameter is not equal to zero. We do not know the true model, and hypothesis testing does not tell us whether the hypothesis is true or false, but if we have enough evidence to reject H<span class="math inline">\(_0\)</span>, then we might conclude that we see an effect of one variable on the other one in the data.</p>
<p>After formulating the hypothesis, we select the significance level. Fro this exercise, we will choose 5%.</p>
<p>Then, we need to select the test to use. As discussed earlier in this chapter, if we can assume that the Central Limit Theorem holds (typically, for the linear regression estimated using the OLS, on samples of more than 50 observations, it does), we can use the Normal distribution. But given that the standard deviations of parameters are not known, and are estimated, we need to use Student’s t distribution. The formula for calculating the t-statistics is fundamentally similar to the one in Section <a href="hypothesisTestingBasics.html#hypothesisTestingBasics">7.1</a>:
<span class="math display" id="eq:ttestFormulaReg">\[\begin{equation}
t = \frac{|b_i - 0|}{s_{b_i}} ,
\tag{12.21}
\end{equation}\]</span>
where <span class="math inline">\(b_i\)</span> is the estimate of the parameter <span class="math inline">\(\beta_i\)</span> and <span class="math inline">\(s_{b_i}\)</span> is the standard error of the parameter obtained from the covariance matrix from Section <a href="uncertaintyRegressionCov.html#uncertaintyRegressionCov">12.1</a>. The standard deviation of the parameter is:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="uncertaintyRegressionHypothesis.html#cb199-1" tabindex="-1"></a><span class="fu">vcov</span>(costsModelMLR)[<span class="dv">2</span>,<span class="dv">2</span>] <span class="sc">|&gt;</span> <span class="fu">sqrt</span>()</span></code></pre></div>
<pre><code>## [1] 0.3111558</code></pre>
<p>Inserting the values in formula <a href="uncertaintyRegressionHypothesis.html#eq:ttestFormulaReg">(12.21)</a> gives us the t-statistics value for our example:
<span class="math display">\[\begin{equation*}
t = \frac{|0.871 - 0|}{0.311} \approx 2.797
\end{equation*}\]</span>
Now we need to get the critical value of the t-statistics for the selected significance value and <span class="math inline">\(n-k\)</span> degrees of freedom, which in our case are equal to 61-5=56. We chose the significance value of 5%, and we conduct a two-sided test, so we need to split it into two parts (this would be similar to constructing a confidence interval), so we should look at the value of statistics for the 2.5% level. In R, we can get it by running:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="uncertaintyRegressionHypothesis.html#cb201-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">56</span>)</span></code></pre></div>
<pre><code>## [1] -2.003241  2.003241</code></pre>
<p>In this code, we consciously provide the values of the statistics for both tails to keep the connection with the interval. If the calculated value was inside this interval, we would fail to reject the hypothesis. In our case, 2.797 lies outside of these bounds, so we can reject the H<span class="math inline">\(_0\)</span> and conclude that based on our model and the data, we have enough evidence to say that there is an effect of material costs on the overall costs of the project.</p>
<div class="remark">
<p><span id="unlabeled-div-56" class="remark"><em>Remark</em>. </span>The easier way of conducting the two sided test is to compare the t-statistics with the absolute of the critical value. In our case, we would be comparing 2.797 with 2.0032, and we would also conclude that the calculated value lies in the tails of distribution and thus we can reject the H<span class="math inline">\(_0\)</span>.</p>
</div>
<p>An alternative way of testing the hypothesis is by calculating the p-value and comparing it with the significance level. In that case, we would reject the H<span class="math inline">\(_0\)</span> if the p-value is lower than the level. For our example, the p-value can be calculated using the <code>pt()</code> function in R:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="uncertaintyRegressionHypothesis.html#cb203-1" tabindex="-1"></a><span class="fu">pt</span>(<span class="fl">2.797</span>, <span class="dv">56</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.003528358</code></pre>
<p>Given that we conduct the two-tail test, this p-value needs to be multiplied by 2 to get approximately 0.00706. The conclusion that we can draw from this is that we reject the null hypothesis on the 5% significance level.</p>
<p>All of this is done automatically by R if we estimate the model using the basic <code>lm()</code> function from the <code>stats</code> package:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="uncertaintyRegressionHypothesis.html#cb205-1" tabindex="-1"></a><span class="fu">lm</span>(overall<span class="sc">~</span>materials<span class="sc">+</span>size<span class="sc">+</span>projects<span class="sc">+</span>year, <span class="at">data=</span>SBA_Chapter_11_Costs) <span class="sc">|&gt;</span></span>
<span id="cb205-2"><a href="uncertaintyRegressionHypothesis.html#cb205-2" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = overall ~ materials + size + projects + year, data = SBA_Chapter_11_Costs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -101.198  -30.443   -2.157   26.032  108.496 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  614.3227  4337.3590   0.142  0.88788   
## materials      0.8706     0.3112   2.798  0.00704 **
## size           1.3471     0.6989   1.928  0.05898 . 
## projects      -1.5921     3.7971  -0.419  0.67660   
## year          -0.1602     2.1621  -0.074  0.94121   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 43.42 on 56 degrees of freedom
## Multiple R-squared:  0.749,  Adjusted R-squared:  0.7311 
## F-statistic: 41.77 on 4 and 56 DF,  p-value: 3.415e-16</code></pre>
<p>The output above shows the estimates of parameters, the standard errors, the t-values and p-values (called “Pr(&gt;|t|)”).</p>
<div class="remark">
<p><span id="unlabeled-div-57" class="remark"><em>Remark</em>. </span>When working with p-values, there is a temptation to not select the significance level before conducting the test or changing it after obtaining the results. This is one of the typical mistakes that can lead to so called p-hacking, where the interpretation of the results of the experiment are amended to fit better to preferences of analyst. This temptation should be resisted! This and other mistakes related to p-values and hypothesis testing were discussed in Subsection <a href="hypothesisTestingBasics.html#hypothesisTestingMistakes">7.1.1</a>.</p>
</div>
<p>The context of regression also provides a great example, why we never accept the null hypothesis and why in the case of “Fail to reject H<span class="math inline">\(_0\)</span>”, we should not remove a variable (unless we have more fundamental reasons for doing that). Consider an example, where the estimated parameter <span class="math inline">\(b_1=0.5\)</span>, and its standard error is <span class="math inline">\(s_{b_1}=1\)</span>, we estimated a simple linear regression on a sample of 30 observations, and we want to test, whether the parameter in the population is zero (hypothesis <a href="uncertaintyRegressionHypothesis.html#eq:regressionHypothesis01">(12.20)</a>) on 5% significance level. Inserting the values in formula <a href="uncertaintyRegressionHypothesis.html#eq:ttestFormulaReg">(12.21)</a>, we get:
<span class="math display">\[\begin{equation*}
\frac{|0.5 - 0|}{1} = 0.5,
\end{equation*}\]</span>
with the critical value for two-tailed test of <span class="math inline">\(t_{0.025}(30-2)\approx 2.05\)</span>. Comparing t-value with the critical one, we would conclude that we fail to reject H<span class="math inline">\(_0\)</span> and thus the parameter is not statistically different from zero. There is a temptation to remove it from the model, but this would be fundamentally wrong. And here is why.</p>
<p>Consider testing another hypothesis for the same parameter:
<span class="math display">\[\begin{equation*}
\begin{aligned}
\mathrm{H}_0: \beta_1 = 1 \\
\mathrm{H}_1: \beta_1 \neq 1
\end{aligned} .
\end{equation*}\]</span>
The procedure is the same, the calculated t-value is:
<span class="math display">\[\begin{equation*}
\frac{|0.5 - 1|}{1} = 0.5,
\end{equation*}\]</span>
which leads to exactly the same conclusion as before: on 5% significance level, we fail to reject the new H<span class="math inline">\(_0\)</span>, so the value is not distinguishable from 1. So, which of the two conclusions is correct? Is it zero or is it one?</p>
<p>The correct answer is “<strong>we do not know</strong>”. The non-rejection region just tells us that the uncertainty about the parameter is so high that it also includes the value of interest (0 in case of the classical regression analysis or 1 in the case of the second hypothesis). If we constructed the confidence interval for this problem, we would not have such confusion, as we would conclude that on 5% significance level the true parameter lies in the region <span class="math inline">\((-1.46, 2.46)\)</span> and can be any of the numbers between them.</p>
</div>
<div id="regression-line" class="section level3 hasAnchor" number="12.4.2">
<h3><span class="header-section-number">12.4.2</span> Regression line<a href="uncertaintyRegressionHypothesis.html#regression-line" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, in regression context, we can test another hypothesis, which becomes useful, when many parameters of the model are very close to zero and seem to be insignificant on the selected level:
<span class="math display" id="eq:regressionHypothesis02">\[\begin{equation}
    \begin{aligned}
        \mathrm{H}_0: \beta_1 = \beta_2 = \dots = \beta_{k-1} = 0 \\
        \mathrm{H}_1: \beta_1 \neq 0 \vee \beta_2 \neq 0 \vee \dots \vee \beta_{k-1} \neq 0
    \end{aligned} ,
\tag{12.22}
\end{equation}\]</span>
which translates into normal language as:
<span class="math display">\[\begin{equation*}
    \begin{aligned}
        \mathrm{H}_0: \text{ all parameters (except for intercept) are equal to zero}\\
        \mathrm{H}_1: \text{ at least one parameter is not equal to zero}
    \end{aligned} .
\end{equation*}\]</span>
This hypothesis is only needed when you have a model with many statistically insignificant variables and want to see if overall the model explains anything. This is done using F-test, which can be calculated based on sums of squares (discussed in Subsection <a href="linearRegressionSimpleQualityOfFit.html#linearRegressionSimpleQualityOfFitSSE">10.4.1</a>):
<span class="math display">\[\begin{equation*}
F = \frac{ SSR / (k-1)}{SSE / (n-k)} \sim F(k-1, n-k) ,
\end{equation*}\]</span>
where the sums of squares are divided by their degrees of freedom. The test is conducted in the similar manner as any other test (see Section <a href="hypothesisTesting.html#hypothesisTesting">7</a>): after choosing the significance level, we calculate the F-value and then either select the critical value of F for the specific degrees of freedom, or compare the significance level with the p-value from the test to make a conclusion about the null hypothesis.</p>
<p>There are several things to consider about the F-test in regression:</p>
<ul>
<li>It is not very useful, when at least one parameter is statistically significant. It only becomes useful in difficult situations of poor fit.</li>
<li>The test on its own does not tell if the model is good or bad, adequate or not, etc.</li>
<li>And the F value and related p-value are not comparable with respective values of another models.</li>
</ul>
<p>Visually, this test checks, whether in the true model the slope of the line on the plot of actuals vs fitted is different from zero. An example with the same costs model is provided in Figure <a href="uncertaintyRegressionHypothesis.html#fig:costsModelHypothesesF">12.12</a>.</p>
<div class="figure"><span style="display:block;" id="fig:costsModelHypothesesF"></span>
<img src="Svetunkov---Statistics-for-Business-Analytics_files/figure-html/costsModelHypothesesF-1.png" alt="Graphical presentation of F-test for regression model." width="672" />
<p class="caption">
Figure 12.12: Graphical presentation of F-test for regression model.
</p>
</div>
<p>What the F-test is about, is whether in the true model (population data) the blue line coincides with the red line (i.e. the slope is equal to zero, which is only possible, when all parameters are zero). If given the data and the model, we have enough evidence to reject the null hypothesis, then this means that the slopes are probably different on the selected significance level.</p>
<p>Here is an example with the costs model discussed in this chapter with the pre-selected significance level of 5%:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="uncertaintyRegressionHypothesis.html#cb207-1" tabindex="-1"></a><span class="co"># Estimate the regression using lm </span></span>
<span id="cb207-2"><a href="uncertaintyRegressionHypothesis.html#cb207-2" tabindex="-1"></a>costsModelMLRLm <span class="ot">&lt;-</span> <span class="fu">lm</span>(overall<span class="sc">~</span>materials<span class="sc">+</span>size<span class="sc">+</span>projects<span class="sc">+</span>year,</span>
<span id="cb207-3"><a href="uncertaintyRegressionHypothesis.html#cb207-3" tabindex="-1"></a>                      <span class="at">data=</span>SBA_Chapter_11_Costs)</span>
<span id="cb207-4"><a href="uncertaintyRegressionHypothesis.html#cb207-4" tabindex="-1"></a><span class="co"># Get summary statistics</span></span>
<span id="cb207-5"><a href="uncertaintyRegressionHypothesis.html#cb207-5" tabindex="-1"></a>costsModelMLRF <span class="ot">&lt;-</span> <span class="fu">summary</span>(costsModelMLRLm)<span class="sc">$</span>fstatistic</span>
<span id="cb207-6"><a href="uncertaintyRegressionHypothesis.html#cb207-6" tabindex="-1"></a><span class="co"># Extract the F-value</span></span>
<span id="cb207-7"><a href="uncertaintyRegressionHypothesis.html#cb207-7" tabindex="-1"></a>costsModelMLRF[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>##    value 
## 41.77388</code></pre>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="uncertaintyRegressionHypothesis.html#cb209-1" tabindex="-1"></a><span class="co"># Calculate the critical value of F</span></span>
<span id="cb209-2"><a href="uncertaintyRegressionHypothesis.html#cb209-2" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, costsModelMLRF[<span class="dv">2</span>], costsModelMLRF[<span class="dv">3</span>])</span></code></pre></div>
<pre><code>## [1] 2.536579</code></pre>
<p>In the output above, the critical value is lower than the calculated, so we can reject the H<span class="math inline">\(_0\)</span>, which means that there is something in the model that explains the variability of the overall costs. Alternatively, we could focus on the p-value:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="uncertaintyRegressionHypothesis.html#cb211-1" tabindex="-1"></a><span class="co"># p-value from the test</span></span>
<span id="cb211-2"><a href="uncertaintyRegressionHypothesis.html#cb211-2" tabindex="-1"></a><span class="fu">pf</span>(costsModelMLRF[<span class="dv">1</span>], costsModelMLRF[<span class="dv">2</span>], costsModelMLRF[<span class="dv">3</span>], <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##        value 
## 3.414938e-16</code></pre>
<p>We see that the the p-value is lower than the significance level of 5%, so we reject the H<span class="math inline">\(_0\)</span> on that level and come to the same conclusion as above. All of this is also provided by default in the summary of the model estimated using the <code>lm()</code> function:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="uncertaintyRegressionHypothesis.html#cb213-1" tabindex="-1"></a><span class="fu">summary</span>(costsModelMLRLm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = overall ~ materials + size + projects + year, data = SBA_Chapter_11_Costs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -101.198  -30.443   -2.157   26.032  108.496 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  614.3227  4337.3590   0.142  0.88788   
## materials      0.8706     0.3112   2.798  0.00704 **
## size           1.3471     0.6989   1.928  0.05898 . 
## projects      -1.5921     3.7971  -0.419  0.67660   
## year          -0.1602     2.1621  -0.074  0.94121   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 43.42 on 56 degrees of freedom
## Multiple R-squared:  0.749,  Adjusted R-squared:  0.7311 
## F-statistic: 41.77 on 4 and 56 DF,  p-value: 3.415e-16</code></pre>
<p>The summary for the <code>alm()</code> does not provide this information because it has a different philosophy behind it (likelihood, which we will discuss in Chapter <a href="likelihoodApproach.html#likelihoodApproach">16</a>).</p>

</div>
</div>
<!-- </div> -->

            </section>

          </div>
        </div>
      </div>
<a href="uncertaintyRegressionLine.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="dummyVariables.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/config-i1/sba/tree/master/Chapters//12-regression-uncertainty.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["Svetunkov---Statistics-for-Business-Analytics.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
