# Augmented Linear Model {#ALM}
In this chapter we discuss a specific model implemented in `greybox` package, which is called "Augmented Linear Model" (ALM). As the name suggests, this is the model that extends the basic linear regression in several directions. First, it focuses on forecasting using regression (which will be discussed later in this textbook). Second, it introduces a set of distributional assumptions for the response variable, allowing, for example, to construct Laplace or Inverse Gaussian model instead of the Normal one (in this respect, the ALM has some similarities with Generalised Linear Model, GLM. See, for example @Dunn2018). Third, it supports mixture distributions, allowing, for example, to construct a combination of logistic and log normal regressions. This becomes especially useful for intermittent demand and other types of data that contain naturally occurring zeroes. Finally, ALM supports ARIMA elements, but we will discuss this topic later in the textbook.

In this chapter, we discuss all the aforementioned aspects of ALM and show how it can be used in a variety of contexts.

